[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shuttle-service = { version = "0.2", features = ["web-axum"] }
tower-web = "0.3"
tokio = "0.1"
serde = { version = "1.0", features = ["derive"] }
