[package]
name = "tide-with-torch"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tide = "0.16.0"
shuttle-service = { version = "0.2.6", features = ["web-tide"] }
tch = "0.7.2"
