name: cargo-test

on:
  push:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml"]
  pull_request:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml"]

  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo_test:
    strategy:
      fail-fast: true
      matrix:
        features: ["web-axum", "web-rocket", "web-tide", "web-tower"]
    runs-on: self-hosted
    steps:
      - uses: shuttle-hq/checkout@v2
      - uses: shuttle-hq/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run integrated test with ${{ matrix.features}}
        run: cargo test --features=${{ matrix.features }} -- --nocapture